const fs = require('fs');
const path = require('path');

// Icono Premium "GEO"
const base64Data = "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAACXBIWXMAAAsTAAALEwEAmpwYAAAFm0lEQVR4nO2dS2hcVRSGv3OnmbSJto0v0mAnmIqID6pFRUQLKig+8AEVQUVQUXzgg4qgIqiID3xARVARVMQHPqCCiqAiPigoSBEfVB9S/P6p7Ywm08y95869p5m2idMmmUmTmf2vltl7Zp0zc8/95xyu9xwAAMDvEAAAAAIUAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkEGlUunpZ+SDAXAbI7E9B8BfQAEAAAhQAACAAAUAAKBAAQAASFAAAAAIUAACAAAUAAKBAABIAAAAIEABAAAoUAAAAAIUAAAIUAAAkMHn+w16AAAAAElFTkSuQmCC".replace(/^data:image\/png;base64,/, "");

const outputPath = path.join(__dirname, 'GEO_ICON.png');

fs.writeFile(outputPath, base64Data, 'base64', (err) => {
    if (err) {
        console.error("Error creando el archivo:", err);
    } else {
        console.log("-----------------------------------------");
        console.log("¡ÉXITO! Se ha creado el archivo:");
        console.log(outputPath);
        console.log("-----------------------------------------");
        console.log("USA ESTE ARCHIVO PARA CAMBIAR EL ICONO DE TU CARPETA.");
    }
});
